export const LOCATION_LOADING = "location-loading"
export const AUTH_LOADING = "loading-auth"

export const PROMISE_CONTRIBUTION_TEMPLATE = `<h2>Promise</h2><ul><li><strong>Made On: </strong></li><li><strong>Expected delivery date: </strong>﻿</li><li><strong>Delivered on:</strong> </li><li><strong>Status:</strong> [Promised, In Progress, Broken e.t.c.]</li></ul><p><br></p><p>[description here]</p><h3>Promise Made By</h3><ul><li>Person A on Behalf of Person B</li><li>Person B for themselves</li><li>Office of... in organization...</li></ul><h3>Locations affected</h3><ul><li>Location A...</li></ul><h3>Links to supporting articles and documents</h3><ul><li>link...</li></ul><h3>Any other Details</h3><p>[add here]</p>`
export const EVENT_CONTRIBUTION_TEMPLATE = `<h2>Event Description</h2><p>[description here]</p><p><br></p><h3>Organized By</h3><ul><li>Person A</li><li>Person B</li><li>Office of...</li><li>Organization...</li></ul><h3>Links to supporting articles and documents</h3><ul><li>link...</li></ul><h3>Any other Details</h3><p>[add here]</p><p>[if this event affects certain promises this is the place to add that information...]</p>`
export const LOCATION_CONTRIBUTION_TEMPLATE = `<h2>[Location Name]</h2><p>[Flag: upload image or add a link]</p><p>[description here]</p><p><br></p><h3>Locate in</h3><ul><li>Continent</li><li>Region e.t.c.</li></ul><h3>Links to supporting articles and documents</h3><ul><li>link...</li></ul><h3>Any other Details</h3><p>[add here]</p>`
export const PERSON_CONTRIBUTION_TEMPLATE = `<h2>[Person Name]</h2><p>[Photo: upload image or add a link]</p><p>[description here]</p><p><br></p><h3>Offices Held</h3><p>Details about offices held by this person in various organizations</p><ul><li>Office A (1999-2003) (retired)</li><li>Office B (2004-2030) (occupying)</li><li>Office C (vying for)</li></ul><h3>Links to supporting articles and documents</h3><ul><li>link...</li></ul><h3>Any other Details</h3><p>[add here]</p>`
export const OFFICE_CONTRIBUTION_TEMPLATE = `<h2>[Office Name]</h2><p>[description here(function, mandate, answers to...)]</p><h3><br></h3><h3>Links to supporting articles and documents</h3><ul><li>link...</li></ul><h3>Any other Details</h3><p>[add here]</p>`
export const ORGANIZATION_CONTRIBUTION_TEMPLATE = `<h2>[Organization Name]</h2><p>[description here]</p><h3><br></h3><h3>Jurisdictions</h3><p>[locations the organization operates in]</p><p><br></p><h3>Links to supporting articles and documents</h3><ul><li>link...</li></ul><h3>Any other Details</h3><p>[add here]</p>`
